name: alfai
description: "ALFAI"
version: 0.0.1+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: 5.8.0+1
  easy_localization: 3.0.7+1
  json_annotation: 4.9.0
  provider: 6.1.2
  shared_preferences: 2.5.2
  stacked: 3.4.4
  timeago: 3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: 6.9.4

flutter:
  uses-material-design: true

  assets:
  - assets/lang/